---
deployment:
      tasks:
        - export DEPLOYPATH=/home/maspriya/Frantinco      # Add /<app_folder> if required
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
        
